/**
 * @file Content script for YouTube transcript and chapter extraction
 */
(function () {
  'use strict';

  var config = globalThis.SVD_CONFIG;

  // --- Extract ytInitialPlayerResponse from the page ---
  function getPlayerResponse() {
    return new Promise(function (resolve) {
      var script = document.createElement('script');
      script.textContent =
        'document.currentScript.dataset.result = JSON.stringify(' +
        '(function(){' +
        'try{' +
        'var p = window.ytInitialPlayerResponse;' +
        'if(!p) return null;' +
        'var chaptersData = null;' +
        'try{' +
        'var d = window.ytInitialData;' +
        'if(d){' +
        'var po = d.playerOverlays;' +
        'if(po && po.playerOverlayRenderer && po.playerOverlayRenderer.decoratedPlayerBarRenderer){' +
        'var dpb = po.playerOverlayRenderer.decoratedPlayerBarRenderer.decoratedPlayerBarRenderer;' +
        'if(dpb && dpb.playerBar && dpb.playerBar.multiMarkersPlayerBarRenderer){' +
        'chaptersData = dpb.playerBar.multiMarkersPlayerBarRenderer.markersMap;' +
        '}' +
        '}' +
        '}' +
        '}catch(e){}' +
        'return {captions:p.captions||null, videoDetails:p.videoDetails||null, chaptersData:chaptersData};' +
        '}catch(e){return null;}' +
        '})()' +
        ');';
      document.documentElement.appendChild(script);
      var result = null;
      try {
        result = JSON.parse(script.dataset.result || 'null');
      } catch (e) { /* ignore */ }
      script.remove();
      resolve(result);
    });
  }

  // --- Extract caption tracks and fetch transcript ---
  async function fetchTranscript(playerData) {
    if (!playerData || !playerData.captions) {
      return null;
    }

    var trackList = playerData.captions.playerCaptionsTracklistRenderer;
    if (!trackList || !trackList.captionTracks || trackList.captionTracks.length === 0) {
      return null;
    }

    // Prefer manual captions over auto-generated
    var tracks = trackList.captionTracks;
    var selectedTrack = tracks.find(function (t) { return t.kind !== 'asr'; }) || tracks[0];

    var url = selectedTrack.baseUrl;
    if (!url) return null;

    // Fetch JSON format
    var separator = url.indexOf('?') >= 0 ? '&' : '?';
    var response = await fetch(url + separator + 'fmt=json3');
    if (!response.ok) return null;

    var data = await response.json();
    if (!data || !data.events) return null;

    // Parse events into segments with timestamps
    var segments = [];
    for (var i = 0; i < data.events.length; i++) {
      var event = data.events[i];
      if (!event.segs) continue;

      var text = '';
      for (var j = 0; j < event.segs.length; j++) {
        text += event.segs[j].utf8 || '';
      }
      text = text.replace(/\n/g, ' ').trim();
      if (!text) continue;

      segments.push({
        startMs: event.tStartMs || 0,
        durationMs: event.dDurationMs || 0,
        text: text
      });
    }

    return {
      segments: segments,
      language: selectedTrack.languageCode || '',
      isAutoGenerated: selectedTrack.kind === 'asr',
      trackName: selectedTrack.name ? (selectedTrack.name.simpleText || '') : ''
    };
  }

  // --- Extract chapters from video ---
  function extractChapters(playerData) {
    var chapters = [];

    // Try from ytInitialData markers (most reliable)
    if (playerData && playerData.chaptersData) {
      try {
        var markersMap = playerData.chaptersData;
        for (var i = 0; i < markersMap.length; i++) {
          var entry = markersMap[i];
          if (entry.value && entry.value.chapters) {
            var chapterList = entry.value.chapters;
            for (var j = 0; j < chapterList.length; j++) {
              var ch = chapterList[j].chapterRenderer;
              if (ch) {
                chapters.push({
                  title: ch.title ? (ch.title.simpleText || '') : '',
                  startMs: ch.timeRangeStartMillis || 0
                });
              }
            }
            break;
          }
        }
      } catch (e) { /* ignore */ }
    }

    // Fallback: parse description for timestamps
    if (chapters.length === 0) {
      chapters = parseDescriptionChapters();
    }

    return chapters;
  }

  // --- Parse chapters from video description timestamps ---
  function parseDescriptionChapters() {
    var chapters = [];
    var descEl = document.querySelector(
      '#description-inner, ' +
      '#description ytd-text-inline-expander, ' +
      'ytd-text-inline-expander#description-inline-expander'
    );
    if (!descEl) return chapters;

    var descText = descEl.innerText || '';
    var lines = descText.split('\n');
    var timestampRegex = /^(?:(\d{1,2}):)?(\d{1,2}):(\d{2})\s+(.+)/;

    for (var i = 0; i < lines.length; i++) {
      var match = lines[i].trim().match(timestampRegex);
      if (match) {
        var hours = match[1] ? parseInt(match[1], 10) : 0;
        var minutes = parseInt(match[2], 10);
        var seconds = parseInt(match[3], 10);
        var startMs = (hours * 3600 + minutes * 60 + seconds) * 1000;
        chapters.push({
          title: match[4].trim(),
          startMs: startMs
        });
      }
    }

    return chapters;
  }

  // --- Split transcript segments by chapter boundaries ---
  function splitByChapters(segments, chapters, videoDurationMs) {
    if (chapters.length === 0) {
      return createTimeChunks(segments, videoDurationMs);
    }

    var result = [];
    for (var i = 0; i < chapters.length; i++) {
      var startMs = chapters[i].startMs;
      var endMs = (i + 1 < chapters.length) ? chapters[i + 1].startMs : (videoDurationMs || Infinity);

      var chapterText = '';
      for (var j = 0; j < segments.length; j++) {
        var seg = segments[j];
        if (seg.startMs >= startMs && seg.startMs < endMs) {
          chapterText += (chapterText ? ' ' : '') + seg.text;
        }
      }

      result.push({
        title: chapters[i].title,
        startMs: startMs,
        endMs: endMs,
        text: chapterText.trim()
      });
    }

    return result;
  }

  // --- Create time-based chunks when no chapters exist ---
  function createTimeChunks(segments, videoDurationMs) {
    var chunkDuration = config.DEFAULT_CHAPTER_DURATION_MS;
    var totalDuration = videoDurationMs ||
      (segments.length > 0 ? segments[segments.length - 1].startMs + 10000 : 0);
    var numChunks = Math.max(1, Math.ceil(totalDuration / chunkDuration));
    var chunks = [];

    for (var i = 0; i < numChunks; i++) {
      var startMs = i * chunkDuration;
      var endMs = Math.min((i + 1) * chunkDuration, totalDuration);

      var chunkText = '';
      for (var j = 0; j < segments.length; j++) {
        if (segments[j].startMs >= startMs && segments[j].startMs < endMs) {
          chunkText += (chunkText ? ' ' : '') + segments[j].text;
        }
      }

      if (chunkText.trim()) {
        chunks.push({
          title: null,
          startMs: startMs,
          endMs: endMs,
          text: chunkText.trim()
        });
      }
    }

    return chunks;
  }

  // --- Get video metadata ---
  function getVideoMetadata(playerData) {
    var details = playerData && playerData.videoDetails ? playerData.videoDetails : {};
    return {
      title: details.title || document.title.replace(/ - YouTube$/, ''),
      author: details.author || '',
      lengthSeconds: parseInt(details.lengthSeconds, 10) || 0,
      videoId: details.videoId || ''
    };
  }

  // --- Format milliseconds to timestamp string ---
  function formatTimestamp(ms) {
    var totalSeconds = Math.floor(ms / 1000);
    var hours = Math.floor(totalSeconds / 3600);
    var minutes = Math.floor((totalSeconds % 3600) / 60);
    var seconds = totalSeconds % 60;
    if (hours > 0) {
      return hours + ':' + String(minutes).padStart(2, '0') + ':' + String(seconds).padStart(2, '0');
    }
    return minutes + ':' + String(seconds).padStart(2, '0');
  }

  // --- Main extraction handler ---
  async function handleExtractTranscript() {
    try {
      var playerData = await getPlayerResponse();
      if (!playerData) {
        return { success: false, error: 'noPlayerData' };
      }

      var metadata = getVideoMetadata(playerData);
      var transcript = await fetchTranscript(playerData);
      if (!transcript || transcript.segments.length === 0) {
        return { success: false, error: 'noSubtitles', metadata: metadata };
      }

      var chapters = extractChapters(playerData);
      var videoDurationMs = metadata.lengthSeconds * 1000;
      var chapterSegments = splitByChapters(transcript.segments, chapters, videoDurationMs);

      // Build full transcript text
      var fullText = transcript.segments.map(function (s) { return s.text; }).join(' ');

      return {
        success: true,
        data: {
          metadata: metadata,
          transcript: {
            fullText: fullText,
            language: transcript.language,
            isAutoGenerated: transcript.isAutoGenerated,
            charCount: fullText.length
          },
          chapters: chapterSegments.map(function (ch) {
            return {
              title: ch.title,
              startMs: ch.startMs,
              endMs: ch.endMs,
              text: ch.text,
              startLabel: formatTimestamp(ch.startMs),
              endLabel: formatTimestamp(ch.endMs)
            };
          }),
          hasChapters: chapters.length > 0
        }
      };
    } catch (err) {
      return {
        success: false,
        error: 'extractionFailed',
        message: err.message
      };
    }
  }

  // --- Message listener ---
  chrome.runtime.onMessage.addListener(function (message, sender, sendResponse) {
    if (message.type === config.MESSAGES.EXTRACT_TRANSCRIPT) {
      handleExtractTranscript().then(sendResponse);
      return true;
    }
    if (message.type === 'seekVideo') {
      var video = document.querySelector('video');
      if (video) {
        video.currentTime = message.seconds;
      }
      sendResponse({ success: true });
      return true;
    }
  });

  // --- YouTube SPA navigation detection ---
  document.addEventListener('yt-navigate-finish', function () {
    chrome.runtime.sendMessage({
      type: 'ytNavigate',
      url: window.location.href
    }).catch(function () {});
  });
})();
